CREATE DATABASE participant_2_controlplane;
CREATE DATABASE participant_1_dataplane;
CREATE DATABASE participant_1_identityhub;
CREATE DATABASE participant_2_dataplane;
CREATE DATABASE participant_2_identityhub;
